/* Generated By:JavaCC: Do not edit this line. CostsParserConstants.java */
package parser.set.langcosts;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CostsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 7;
  /** RegularExpression Id. */
  int PAR = 8;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 9;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 10;
  /** RegularExpression Id. */
  int DEF = 11;
  /** RegularExpression Id. */
  int AND = 12;
  /** RegularExpression Id. */
  int OR = 13;
  /** RegularExpression Id. */
  int ARROW = 14;
  /** RegularExpression Id. */
  int ASSIGNMENT = 15;
  /** RegularExpression Id. */
  int POINT = 16;
  /** RegularExpression Id. */
  int OPEN = 17;
  /** RegularExpression Id. */
  int CLOSE = 18;
  /** RegularExpression Id. */
  int COMMA = 19;
  /** RegularExpression Id. */
  int COST = 20;
  /** RegularExpression Id. */
  int EOL = 21;
  /** RegularExpression Id. */
  int ZERO = 22;
  /** RegularExpression Id. */
  int VALUE = 23;
  /** RegularExpression Id. */
  int NUMBER = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"P\"",
    "\"{\"",
    "\"}\"",
    "\"DEFAULT\"",
    "\"AND\"",
    "\"OR\"",
    "\"=>\"",
    "\"=\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"0\"",
    "<VALUE>",
    "<NUMBER>",
  };

}
