package ui;

import informations.Infos;

public class InfoDialog extends javax.swing.JDialog
{
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;

    /** Creates new form InfoDialog */
    public InfoDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();

        String phylo_v = Infos.PHYLO_NAME + " - "+Infos.PHYLO_VERSION;
        PhyloVersion.setText(phylo_v);

        String jdk = Infos.JDK_NAME+" "+Infos.JDK_VERSION;
        String itext = Infos.ITEXT_NAME+" "+Infos.ITEXT_VERSION;
        String phylip = Infos.PHYLIP_NAME+" "+Infos.PHYLIP_VERSION;

        String about = "Phylo is a Phylogenetic Framework programmed "
                     + "with "+jdk+" and made for the <a href=\"www.units.it\">University of Trieste</a>."
                     + "It includes "+itext+", fitch, kitsch, neighbor, "
                     + "consense algorithms from "+phylip+" package "
                     + "and SwingWorker from JDK 1.6 source code.";

        jEditorPane1.setText(about);

        String who = "Author: "+Infos.AUTHOR +" <"+Infos.AUTHOR_EMAIL+">";
        WhoLabel.setText(who);
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        PhyloVersion = new javax.swing.JLabel();
        WhoLabel = new javax.swing.JLabel();
        jEditorPane1 = new javax.swing.JEditorPane();

        setTitle("About Phylo");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        PhyloVersion.setFont(new java.awt.Font("Monospaced", 1, 24));
        PhyloVersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/phylo.png"))); // NOI18N
        PhyloVersion.setText("text");

        WhoLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jEditorPane1.setBorder(null);
        jEditorPane1.setContentType("text/html");
        jEditorPane1.setEditable(false);
        jEditorPane1.setFont(new java.awt.Font("Lucida Sans", 0, 12));
        jEditorPane1.setOpaque(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(PhyloVersion))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(288, Short.MAX_VALUE)
                        .add(closeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 81, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jEditorPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                            .add(WhoLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(PhyloVersion)
                .add(18, 18, 18)
                .add(jEditorPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                .add(WhoLabel)
                .add(18, 18, 18)
                .add(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_closeButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InfoDialog dialog = new InfoDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PhyloVersion;
    private javax.swing.JLabel WhoLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JEditorPane jEditorPane1;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
